### ISSUE TITLE
May 6, 2024 - Progress Checking

### ISSUE THREAD

**Issue by LebHermo** [LebHermo/chardin-react-node#17]
### General
- [ ] Clean console issues 
- [x] Font should be reverted to Inter
- [ ] Remove unecessary and unused dependencies
- [ ] Please replace all modals with bootstrap modal, no additional dependencies to increase loading time. 
- [ ] Launch the website @joshuaRLB 
- [x] Brand icon @dragona089 
- [x] Doble doble ang routes sa App.js 

### Homepage
- [ ] Navbar responsiveness @LebHermo 
- [x] Improve gallery interface @LebHermo 
- [x] Gallery slick-dots to appropriate color @LebHermo 
- [x] Add Section Title in About Us section @LebHermo 
`- [ ] Update "About Us" Image @LebHermo `

### Order Tracking Page
- [x] Empty field still returns "Order not Found"
- [x] Inputting correct order ID still returns "Order not Found"
- [x] Improve "Not Found" modal interface @LebHermo 

### Login
- [x] Change login image? @LebHermo 
- [ ] Should put session timeout for security purposes
- [x] Pressing logout redirects me to dashboard and does not allow me to log out

### Admin/Dashboard
- [x] Improve image interface @LebHermo 
`- [ ] Change profile image to Chardin image @LebHermo `
- [x] On refresh, admin always redirects to dashboard
- [ ] Shown profile should be username, not email
- [ ] Uploaded image not showing on preview

### Admin/Orders
- [x] Orders' Table UI shoud be reverted to original @LebHermo 
- [ ] Multiple items per order. please.
- [x] Revert UI based on original interface @LebHermo 
- [x] Should add "More Details" section to view all products, more info (e.g. cust. address, contact number, etc.)
- [ ] Order ID (given to customers) should be displayed
- [ ] Truncating texts should be "..." not ",,,"
- [ ] Orders should be on descending order (latest to oldest)
- [x] Pagination missing @LebHermo 
- [ ] Modal should have a "Order Added by:" to know who added the order 

### Admin/AddOrder
- [x] Event date should be Due Date
- [ ] Add "Date Ordered"
- [ ] "Orders" should be active on sidebar when this page is loaded
- [ ] "Filled Date" should automatically be filled with current date
- [x] Edit statuses to new statuses: Designing, Creation in Progress, Available for Pickup, Completed, Cancelled
- [x] Balance should never be negative
- [ ] Remove "Please fill all required fields", instead, make required fields "required" and put error message under the field.

### Admin/EditOrder
- [ ] Turn text color to white (mura siyag placeholder) @LebHermo 
- [x] Dates are not automatically filled
- [x] "Proceed to Order" button should be "Update Order" button
- [ ] Deposit amount should be added, not edited

### Admin/Users
- [x] Users' Table UI should be reverted to original @LebHermo 
- [ ] Should have "date added" and "added by"
- [x] Should have an edit user option 
- [ ] Pagination missing

### Admin/AddUser
- [ ] Back button doesn't work
- [ ] "Users" should be active on sidebar when this page is loaded @LebHermo 
- [x] Should add "Date added" per user and which user added it

### Design Custom Tool @dragona089 
- [ ] Medium window responsiveness
- [ ] Mobile responsiveness

### Payments Page
- [x] Payment Gateway should not be visible/required when Payment Method = Cash is selected
- [ ] Sort by not functioning
- [ ] Search bar not functioning
- [x] Should not successfully Add Payment if OrderID is invalid

**Comment by joshuaRLB** [comment]
Kani rA?
Track order restriction if wala gi search mag display fill up, if mali ang tracking kay display no order exist if tama show modal

AddOrder i change ang dates to filled date ug DueDate(EventDate)
AddOrder fix ang modal confirmation then mag show firebase Id if order added successful

OrderPage dapat ma click ug ma view ang Order

adminPages session makita sa top left

**Comment by LebHermo** [comment]
Closed due to updated issues in newer issue
